version: "3.8"
services:
  nginx:
    restart: always
    image: nginx
    ports:
      - 8089:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  server1:
    image: server1
    ports:
      - 3001:3000
  server2:
    image: server2
    ports:
      - 3002:3000
  server3:
    image: server3
    ports:
      - 3003:3000